CREATE TABLE  all_retail_sales
( 
Transaction_ID text, 
Customer_ID text, 
Full_Name text, 
Email text,
Phone text, 
Address text, 
City text, 
State text, 
Zipcode int, 
Country text, 
Age tinyint, 
Gender text, 
Income text, 
Customer_Segment text, 
Date text, 
Year text, 
Month text, 
Time text, 
Total_Purchases int, 
Amount int, 
Total_Amount int, 
Product_Category text, 
Product_Brand text, 
Product_Type text, 
Feedback text, 
Shipping_Method text, 
Payment_Method text, 
Order_Status text, 
Ratings tinyint, 
Products text,
); 

